### PR TITLE
PackageInfo.g: add License field

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by ChrisJefferson** [comment]
I can't add a single licence field, as there are two licensez being used, mit and cddl.

**Comment by fingolfin** [comment]
It's still difficult to determine the license of this package. Would be good if the README explained it.

And of course SPDX allows specifying all kinds of license combinations. Am on the phone, can update the PR later ; though of course you could also look it up yorself :-)

**Comment by ChrisJefferson** [comment]
The license file does discuss the various license bits (although that file is new!)

**Comment by ChrisJefferson** [comment]
... I didn't push the license file.

**Comment by fingolfin** [comment]
Ahh, that explains why I didn't find it when I looked for it earlier :-)

**Comment by fingolfin** [comment]
Updated to use the correct SPDX license identifier `MIT AND CDDL-1.0`

**Comment by ChrisJefferson** [comment]
I don't mind merging this, but it really does feel like busywork. I mean, we seem to now require it, but do absolutely nothing with it?

**Comment by alex-konovalov** [comment]
@ChrisJefferson this was suggested in https://github.com/gap-system/gap/issues/997 and had no objections. Next steps, as explained there, are:
- update website scripts that extract details from PackageInfo.g for package overview pages
- update GitHubPagesForGAP to display license information

**Pull request merged**
