### PR TITLE
Fix a compiler warning in RapidJSON headers, and convert those from Windows to Unix line ends

### PR DESCRIPTION
**Pull request by fingolfin**

### CODE REVIEW

**Comment by fingolfin** [comment]
@ChrisJefferson ping

**Comment by ChrisJefferson** [comment]
I'm confused, what is the actual change? (It looks like you've changed the whole file?)

**Comment by fingolfin** [comment]
There are three commits, best to look at them separately

**Comment by fingolfin** [comment]
@ChrisJefferson in particular, in the first commit, indeed the whole file is changed, to fix the line endings. The second commit removes an executable bit, and the final one fixes the warning.

**Comment by ChrisJefferson** [comment]
I did that :) try clicking on the third commit, it just shows one file entirely changed

**Comment by fingolfin** [comment]
@ChrisJefferson Aaargh, sorry, I didn't understand that bit. Fixed now!

**Pull request merged**
